### ISSUE TITLE
How to link?

### ISSUE THREAD

**Issue by felschr** [zillemarco/StarUML_LinkedDiagramNavigator#1]
First of all thanks for this extension! It's really great.
But I still have some problems figuring out how to link elements to be able to use this feature.

I was able to:
- link a use case in a use case diagram to a sequence diagram by adding an "Interaction" as a child of the use case and adding the sequence diagram as a child of that interaction and checking the "defaultDiagram" checkbox.

But for some reason, I cannot link a subsystem in a package diagram to a (use case) diagram under that subsystem.

Could you maybe list which elements can be linked and how?

**Comment by zillemarco** [comment]
I don't thick you can actually. What my extension does is simply to check if an element of the diagram has another diagram linked to it, allowing you to navigate to it directly.
Linking a use case with an activity diagram is straight forward by doing:

1. Add a use case to a use case diagram
2. Right-click on the added use case
3. From the context menu select Add->Activity
4. On the model explorer right click and the just added activity
5. From the context menu select Add Diagram->Activity Diagram
6. Now the use case is linked to the activity diagram

Now, to answer your question, I just tried to do the same but with a subsystem and a use case diagram like you want.

1. Add a subsystem to a package diagram
2. Right-click on the added subsystem
3. From the context menu select Add->Use case
4. On the model explorer right click and the just added use case
5. On the context menu, under the "Add Diagram" voice, there isn't the "Use Case Diagram" voice, and here I think is where the problem is, maybe you just can't add the use case diagram to the subsystem.

Did you do like I did or have you tried with a different approach?

**Comment by felschr** [comment]
Hmm.
I added the use case diagram directly under the subsystem instead of under a use case.
Also adding use cases as children of a use case diagram seemed more logical to me,
Probably because the context menu on the subsystem allowed adding use case diagrams.

**Comment by zillemarco** [comment]
Oh I see. In fact I was able to add the use case diagram right under the subsystem from the context menu of the subsystem. I'll have a look a what data I'm getting to try to fix this

**Comment by felschr** [comment]
I also tried adding an interaction with underlying sequence diagram to the subsystem.
Just like I did with the working use case to sequence diagram link.
It didn't work. Seems like a general issue with subsystems.

**Comment by zillemarco** [comment]
Yeah, when I made the extension I didn't know that you could add something to an object the way you told me. I've found what the problem is and I'm fixing it now.

**Comment by felschr** [comment]
Great to hear that!
Imo this is the most useful StarUML plugin.

**Comment by zillemarco** [comment]
Fixed the issue for now. I'll be releasing a new version so the change I made will be published.
I found a problem though, if you have more than one diagram linked to an element you will navigare always to the first one. I'll change this to show the list of connected diagrams to let the use chose the diagram he wants to go, but right now I don't have time because I'm busy at work. Possibly in a day or two I'll be able to make this change.

**Comment by felschr** [comment]
I created a pull request to add support to follow a link to a diagram that is set as default.
Showing a list would also be a great addition.

**Comment by zillemarco** [comment]
That's perfect. Thank you very much

**Comment by felschr** [comment]
Could you create a release including these changes?

**Comment by zillemarco** [comment]
Yes sure, I planned it but I've been busy at work. I'll make the release within today.

**Comment by felschr** [comment]
No pressure, mate ;)

**Comment by zillemarco** [comment]
As promised I've created the new release :)
I've also contacted the StartUML team to publish it to their extensions repository.
